### PR TITLE
keep track of on <enter> on charKey change to prevent hiding the resu…

### PR DESCRIPTION
**Pull request by koktaildotcom**
resolves https://github.com/ng2-ui/auto-complete/issues/340

### CODE REVIEW

**Comment by koktaildotcom** [comment]
@almothafar can you look at the pr please?

**Comment by almothafar** [comment]
Thanks for PR, I'm just worried about breaking the correct behavior of this component, I mean when the list opened, and I select the item with arrows, and click enter, does your BR breaking this and force me to click instead? if yes, then I'm not going to merge this, because it will simply create a new issue.

**Comment by koktaildotcom** [comment]
Thanks for your reaction @almothafar. The PR is not breaking the correct behavior of the select list. The code keeps track of current state of the `input` with the `selectOnEnter` variable.

In your scenario:
`selectOnEnter` = `false` on default.
On `arrow up` (or `arrow down`) the event `blur` on `input` wil be triggered this will set  `selectOnEnter` to `true` if now the `enter` is triggered the item is selected.

On `hideDropdownList` the `selectOnEnter` will be set to `false` so the `enter` (without the `autocomplete list open` will not return the item.

I've already have this code running on a production environment.

**Comment by almothafar** [comment]
Sounds good. I'll merge it but it will be released next version.

**Pull request merged**
