### PR TITLE
New property to make auto focus behavior more configurable

### PR DESCRIPTION
**Pull request by igorrius**
Hello! Please see my PR. I had use a new property to make auto focus behavior more configurable. Thanks!

### CODE REVIEW

**Comment by allenhwkim** [comment]
I think we are having too many options.
Can you think other way without introducing a new option?

**Comment by igorrius** [comment]
Maybe you are right, but many option gives us more flexible behavior. So, I promise will think about your propose. Thanks!)

**Comment by troolee** [comment]
I don't thing this is a good solution. As for me, auto-focus should still work when user selects a value.

**Comment by igorrius** [comment]
> I don't thing this is a good solution. As for me, auto-focus should still work when user selects a value.
If you using two components in one form and you change focus between that, first component still be focused. Exactly this problem I was trying to fix.

**Comment by arthursp** [comment]
Could you please merge to master ? This feature is a requirement, as igorrius said, for example i am using it in ionic, and ionic allready set the focus on inputs ...

**Comment by arthursp** [comment]
Could you also publish the npm module with a new version ?

**Comment by spike31** [comment]
Hi,
I think this is strange to have the attribute `re-focus-after-select` on true by default...now I need to pass on all my directives to add this attribute on false.
But thanks to propose a fix.

**Comment by matteobaldelli** [comment]
Why was it implemented only in directive and not in component??

**Pull request merged**
