### PR TITLE
Upgrade Angular 2 to Angular 4 including material upgrade as well + new features

### PR DESCRIPTION
**Pull request by almothafar**
I think we close to Angular 5 and we still on Angular 2 here :)

### CODE REVIEW

**Comment by allenhwkim** [comment]
Please make a PR without a build

**Comment by almothafar** [comment]
@allenhwkim reversed the building commit, I pushed it for my fork but it seems the PR get it directly.

**Comment by allenhwkim** [comment]
Still having conflict. Could you make a PR after resolving the conflict?

**Comment by almothafar** [comment]
@allenhwkim merged with previous pull request

**Comment by allenhwkim** [comment]
The test is failing after the merge. Can you fix the test? e.g., `npm test`

**Comment by almothafar** [comment]
bull request #271 is ready to fix this

**Pull request merged**
