### PR TITLE
Rename "auto-complete-first-item" to "auto-select-first-item"

### PR DESCRIPTION
**Pull request by lemarsu**
Add documentation in README.md too.

This PR is to implement @evasquez26 suggestions.

### CODE REVIEW

**Comment by lemarsu** [comment]
Thanks a lot @allenhwkim for accepting my PR. Could you please publish to npm ?

**Comment by allenhwkim** [comment]
The test `npm run test` is failing on this. change.
I would prefer the publish until the test is fixed(although I found this later)

**Comment by lemarsu** [comment]
I just created PR #248 with passing tests.

The tests failed because the first element is no more selected by default.

**Comment by allenhwkim** [comment]
0.13.5 is published

**Pull request merged**
